# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernel.sysctl = {
    "vm.swappiness" = 40;
    "vm.vfs_cache_pressure" = 50;
    "vm.page-cluster" = 0;
  };

  boot.kernelParams = [
    "zswap.enabled=0"
  ];

  fileSystems."/" = {
    device = "/dev/mapper/cryptdev";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "noatime" # Don't update access time (performance)
      "compress=zstd:1" # Light compression for better I/O
      "discard=async" # Async TRIM for SSD
    ];
  };

  boot.initrd.luks.devices."cryptdev" = {
    device = "/dev/disk/by-uuid/e2a92088-b263-401f-86fd-d12ec2823314";
    allowDiscards = true; # Enable TRIM/discard support for SSD through LUKS
  };

  fileSystems."/var/lib/swap" = {
    device = "/dev/mapper/cryptdev";
    fsType = "btrfs";
    options = [
      "subvol=@swap"
      "noatime"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptdev";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "noatime"
      "compress=zstd:1"
      "discard=async"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0B12-A21A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # swapDevices = [
  #   {
  #     device = "/var/lib/swap/swapfile";
  #     priority = 10;
  #   }
  # ];

  zramSwap = {
    enable = true;
    priority = 100;
    memoryPercent = 85;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
